services:
  image-funnel:
    image: NateScarlet/image-funnel:edge
    # 或者使用 ghcr
    # image: ghcr.io/NateScarlet/image-funnel:edge
    # 或者使用本地构建
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    ports:
      - "34898:80"
    volumes:
      # /app/workspace 是应用根目录，提供外部待筛选图片
      - ./images:/app/workspace
      # /app/data 用于存储应用持久化数据（如密钥）
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
